# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10

  - name: Research
    url: '/research/'
    weight: 20

  # Dropdown items under "Research"
  - name: Presentation of my research
    url: '/research/'
    parent: Research
    weight: 21

  - name: Projects
    url: '/projects'
    parent: Research
    weight: 22

  - name: Publications
    url: '/publication/'
    parent: Research
    weight: 23

  - name: Talks
    url: '/event'
    weight: 30

  - name: Teachings
    url: '/course'
    weight: 40


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
